spring.datasource.url=jdbc:oracle:thin:@oracle-prod:1521/XEPDB1
spring.datasource.username=PUROHITH_PROD
spring.datasource.password=prodpass
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect